export default {
  login: 'POST /auth/login',
  register: 'POST /auth/register',
  getUser: '/v1/user',
  getGuideTypes: '/v1/type/guide',
  getGuides: '/v1/guide',
  getGuide: '/v1/guide/:id',
  addGuide: 'POST /v1/guide',
  putGuide: 'PUT /v1/guide/:id',
  getRoutes: '/v1/route',
  addRoute: 'POST /v1/route',
  putRoute: 'PUT /v1/route/:id',
  addRoutePoi: 'POST /v1/route-poi',
  putRoutePoi: 'PUT /v1/route-poi/:id',
  getPoiTypes: '/v1/type/poi',
  getPois: '/v1/poi',
  addPoi: 'POST /v1/poi',
};
